[package]
name = "has-my-alias-been-pwned"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "A simple application to check email aliases against haveibeenpwned.com"
repository = "https://github.com/gigaSproule/has-my-alias-been-pwned"

[dependencies]
async-trait = "0.1.52"
dotenv = "0.15.0"
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.135", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }

[dev-dependencies]
httpmock = "0.6"
serial_test = "0.6.0"
