version: 2.1

orbs:
  gh: circleci/github-cli@2.7.2

jobs:
  semgrep-scan:
    parameters:
    environment:
      # Scan changed files in PRs, block on new issues only (existing issues ignored)
      # SEMGREP_BASELINE_REF: << parameters.diff_branch >>
      SEMGREP_REPO_URL: << pipeline.project.git_url >>
      SEMGREP_BRANCH: << pipeline.git.branch >>
      # Change job timeout (default is 1800 seconds; set to 0 to disable)
      # SEMGREP_TIMEOUT: 300
    docker:
      - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep scan"
          command: semgrep ci
  test:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout
      - run: cargo test
  build_linux:
    docker:
      - image: rust:latest
    resource_class: small
    steps:
      - checkout
      - run: cargo build --release
      - run: mv target/release/has-my-alias-been-pwned target/release/has-my-alias-been-pwned-linux
      - persist_to_workspace:
          root: target/release/
          paths:
            - has-my-alias-been-pwned-linux
  build_macosx:
    docker:
      - image: joseluisq/rust-linux-darwin-builder:latest
    resource_class: small
    steps:
      - checkout
      - run: cargo build --release --target x86_64-apple-darwin
      - run: mv target/x86_64-apple-darwin/release/has-my-alias-been-pwned target/release/has-my-alias-been-pwned-mac
      - persist_to_workspace:
          root: target/release/
          paths:
            - has-my-alias-been-pwned-mac

  upload_artifacts:
    docker:
      - image: circleci/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - gh/install
      - gh/setup
      - run:
          command: |
            gh release upload $CIRCLE_TAG /tmp/workspace/has-my-alias-been-pwned-linux /tmp/workspace/has-my-alias-been-pwned-mac

workflows:
  version: 2
  test_and_build:
    jobs:
      - semgrep-scan
      - test
      - build_linux:
          requires:
            - test
      - build_macosx:
          requires:
            - test
      - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          files: traget/release/anonaddy-hibp
          requires:
            - build_linux
            - build_macosx
          tag: $CIRCLE_TAG
          title: $CIRCLE_TAG
